Ezeji-Udoka-Akans/Controllers/EducationController.cs
using Ezeji_Udoka_Akans.Models;
using Microsoft.AspNetCore.Mvc;

namespace Ezeji_Udoka_Akans.Controllers
{
    public class EducationController : Controller
    {
        public IActionResult Index()
        {
            var education = new List<EducationModel>
        {
            new EducationModel
            {
                SchoolName = "SCRUMstudy",
                Certificate = "Scrum Fundamentals Certified, SCRUM Methodologies",
                DateTime =     "Oct 2022 - Nov 2022 ",

                Description = "Scrum Fundamentals Certified (SFC®) professionals are facilitators who ensure that the Scrum Team is provided with an environment conducive to completing the project successfully. The Scrum Master guides, facilitates, and teaches Scrum practices to everyone involved in the project; clears impediments for the team and ensures that Scrum processes are being followed."

            },

             new EducationModel
            {
                SchoolName = "Imo State University",
                Certificate = "B.Sc.INDUSTRIAL CHEMISTRY",
                DateTime =     "2012 - 2016",

                Description = ""

            },

              new EducationModel
            {
                SchoolName = "UNIQUE COMPUTER INSTITUTE OWERRI",
                Certificate = "CERTIFICATE IN COMPUTER APPLICATION TO BUSINESS TRANSACTION",
                DateTime =     "2012 - 2012 ",

                Description = "Computer Application in Business is a course designed to train student on\r\nthe use of personal computer in the world of business. The knowledge gained in this course would lead to proficiency in electronic business management."
            },
        };


            return View(education);
        }
    }
}

Ezeji-Udoka-Akans/Controllers/ExperienceController.cs
using Ezeji_Udoka_Akans.Models;
using Microsoft.AspNetCore.Mvc;

namespace Ezeji_Udoka_Akans.Controllers
{
    public class ExperienceController : Controller
    {
        public IActionResult Index()
        {
            var experiences = new List<ExperienceModel>
        {
            new ExperienceModel
            {
                Position = "Back End Developer",
                Company = "Sterling Bank",
                StartDate = new DateTime(2023, 6, 5),
                EndDate = DateTime.Now,
                Description = "• Collaborate with cross-functional teams to understand software requirements and user needs." +
                              "\r\n• Assist in the design and development of software solutions, including coding, testing, debugging, and documentation." +
                              "\r\n• Work on bug fixes and software enhancements to improve existing applications." +
                              "\r\n• Contribute to the maintenance and optimization of databases, APIs, and backend services." +
                              "\r\n• Assist in the identification and resolution of software defects." +
                              "\r\n• Stay up-to-date with emerging software development trends and technologies." +
                              "\r\n• Assist with troubleshooting and providing technical support to end-users as needed." +
                              "\r\n• Collaborate with team members to meet project deadlines and deliver high-quality software solutions."
            },

              new ExperienceModel
            {
                Position = "Full-stack Developer ",
                Company = "Decagon",
                StartDate = new DateTime(2022, 11, 22),
                EndDate = new DateTime(2023, 6, 01),
                Description = "• Build real-time applications that are efficient, scalable, maintainable, extensible, and testable." +
                              "\r\n•Improved and worked on the existing codebase and effectively managed software functionalities" +
                              "\r\n•Produced clean, error-free code to meet aggressive timelines." +
                              "\r\n• IT training of clients/customers employees on the use and maintenance of software functionalities built by our team." +
                              "\r\n• Improve, migrate and work on the existing codebase." +
                              "\r\n•Communicate with business analysts and product owners to clarify requirements in a distributed team environment."
                                                            
            },

              new ExperienceModel
            {
                Position = "Mobile Phone Engineer ",
                Company = "Kawins Global Services",
                StartDate = new DateTime(2018, 03, 22),
                EndDate = new DateTime(2022, 11, 10),
                Description = "•Testing mobile devices to ensure their configuration, operation, and capabilities work efficiently." +
                              "\r\n•Working knowledge of mobile operating systems such as iOS and Android" +
                              "\r\n•Communicate with the customers to listen to and solve their technical issues" +
                              "\r\n• Solving complex technical issues that relate to device management networking and enrollment" +
                              "\r\n• Improving the existing methods and procedures to develop possible alternative solutions from customers." 
                              
            },
        };

            return View(experiences);
        }
    }
}

Ezeji-Udoka-Akans/Controllers/ProjectController.cs
using Ezeji_Udoka_Akans.Models;
using Microsoft.AspNetCore.Mvc;

namespace Ezeji_Udoka_Akans.Controllers
{
    public class ProjectController : Controller
    {
        public IActionResult Index()
        {

            var projects = new List<ProjectModel>
            {
                new ProjectModel
                {
                    Description = "This is a link to my personal Github profile",
                    Tools = "• C#\r\n• .NET\r\n• ASP.NET Core\r\nWEB API\r\n• Entity Framework\r\n• MySQL\r\n• Postman\r\n• Docker\r\n• JavaScript\r\n• HTML 5\r\n• CSS•\r\n Visual Studio\r\n• GitHub\r\n• Azure\r\n• VS Cod ",
                    Name = "GitHubLink",
                    Link = "https://github.com/AKANS22",
                    Role = "Owner"


                },

                new ProjectModel
                {
                    Description = "Certifications by unify is an online learning platform that allows anyone to watch, listen and learn from our everyday STARS. Essentially a MOOC service provider. The goal is to aid people with little or no experience learn from powerfully talented individuals using brilliant storytelling and in-depth learning methods. The vision for Certifications by Certification by unify is to offer knowledge by the second; through practical, funny and engaging video modules. You can learn a trade, improve a passion, advance a career or get inspiration from industry best. These Masterclasses are to be hosted on Certification by unify, an EdTech platform with an all-in-one School Management System that manages and automates the physical operations of universities",
                    Tools = "• C#\r\n•ASP.NET Core WEB API\r\n• Entity Framework\r\n• Postgre\r\n MySQL\r\n• Postman\r\n• Docker\r\n•Visual Studio\r\n Azure",
                    Name = "Certification-By-Unify",
                    Link = "https://certifications.unifyedu.ng",
                    Role = "Back-End Engineer"


                },
            };
            return View(projects);
        }
    }
}

Ezeji-Udoka-Akans/Controllers/SkillsController.cs
using Ezeji_Udoka_Akans.Models;
using Microsoft.AspNetCore.Mvc;

namespace Ezeji_Udoka_Akans.Controllers
{
    public class SkillsController : Controller
    {
        public IActionResult Index()
        {
            var skills = new List<SkillsModel>
        {
            new SkillsModel
            {
               Description = "TECHNOLOGIES",
               Skills = "C#",
               RateLevel = "1-10",
               Rate = 7


            },
            new SkillsModel
            {
               Description = "TECHNOLOGIES",
               Skills      = " ASP.NET Core WEB API",
               RateLevel = "1-10",
               Rate = 7

            },
             new SkillsModel
            {
               Description = "TECHNOLOGIES",
               Skills      = " ASP.NET Core MVC",
               RateLevel = "1-10",
               Rate = 5

            },
              new SkillsModel
            {
               Description = "TECHNOLOGIES",
               Skills      = " Entity Framework",
               RateLevel = "1-10",
               Rate = 7

            },
               new SkillsModel
            {
               Description = "TECHNOLOGIES",
               Skills      = " MySQL",
               RateLevel = "1-10",
               Rate = 7

            },

                new SkillsModel
            {
               Description = "TECHNOLOGIES",
               Skills      = "  Postman",
               RateLevel = "1-10",
               Rate = 7

            },
                 new SkillsModel
            {
               Description = "TECHNOLOGIES",
               Skills      = " Dorker",
               RateLevel = "1-10",
               Rate = 7

            },


                 new SkillsModel
            {
               Description = "TECHNOLOGIES",
               Skills      = "JavaScript",
               RateLevel = "1-10",
               Rate = 6

            },

                 new SkillsModel
            {
               Description = "TECHNOLOGIES",
               Skills      = "CSS",
               RateLevel = "1-10",
               Rate = 6

            },

                 new SkillsModel
            {
               Description = "TECHNOLOGIES",
               Skills      = "HTML",
               RateLevel = "1-10",
               Rate = 6

            },
            new SkillsModel
            {
               Description = "Tools",
               Skills      = "• Visual Studio\r\n• GitHub\r\n• Azure\r\n• VS Code"

            },
        };
            return View(skills);
        }
    }
}

Ezeji-Udoka-Akans/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Ezeji_Udoka_Akans</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Ezeji_Udoka_Akans.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Ezeji_Udoka_Akans</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Experience" asp-action="Index">Experience</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Education" asp-action="Index">Education</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Skills" asp-action="Index">Skills</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Project" asp-action="Index">Project</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Ezeji_Udoka_Akans - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>